### ISSUE TITLE
Feature request: add sensor or dummy device for automation

### ISSUE THREAD

**Issue by ankaerith** [mcclurec/homebridge-volumio-speakers#10]
Homekit doesn't allow you to trigger automations based off of the SmartSpeaker device.  It would be great if you included an option to create a shadow device or sensor that simply tracks the status of VolumIO devices as either playing or not.  This would allow the creation of automations in response to starting and stopping the music.

**Comment by mcclurec** [comment]
That's an interesting idea. I'll play around with adding something as an option. I'm thinking more about using a `sensor` rather than a `switch` since that semantically makes more sense to me. Also, there are no input options to a sensor. 

Fair warning that I don't get a _ton_ of time to tinker on this project, so it may take me a minute 😬

**Comment by mcclurec** [comment]
@ankaerith Done! You should be able to pull version `0.4.0` and have the option to add sensors. Enable them in the config, restart Homebridge, then go to HomeKit and do the Add Accessory dance 👍

**Comment by ankaerith** [comment]
Awesome, thank you it works!

The only slightly unintended behavior I noticed was that it reacts instantly to when music stops streaming (as you'd expect).  When you skip tracks, or ask for a new track VolumIO registers a brief stop in the stream and homekit triggers a rapid on-off automation.    If you're just letting a playlist run it's fine, but as soon as you intervene it hiccups.  

I think I can work around it with some delay switch trickery in an automation string, but if you're looking for other enhancement ideas, it might be neat to have a configurable delay before the sensor turns off.  Basically instant on, but delay off to potentially give the sensor time to reactivate before triggering turn off automatons.

**Comment by ankaerith** [comment]
FYI, delay switch solved the challenge above perfectly:  https://github.com/nitaybz/homebridge-delay-switch

Thanks again for adding this feature.

**Comment by mcclurec** [comment]
Thanks for the info. Glad it's working in general. I should be able to debounce the off state pretty easily. I'll try and find some time to roll that in to here so you don't need to use a second plugin 👍
